"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "fr" | "ar";
type Theme = "light" | "dark";

interface PreferencesContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  t: (key: any) => any;
}

const translations = {
    en: {
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    houses: "Inventory",
    analytics: "Analytics",
    portfolio: "Portfolio",
    schedule: "Schedule",
    settings: "Settings",
    logout: "Logout",
    search_placeholder: "Search properties...",
    my_cards: "My Cards",
    top_picks: "Top Picks",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    preferences: "Preferences",
    profile: "Profile",
    security: "Security",
    connections: "Connections",
    notifications: "Notifications",
    my_cards_title: "My Cards",
    top_picks_title: "Top Picks",
    investment_stats: "Investment Stats",
    my_portfolio: "My Portfolio",
    total_investment: "Total Investment",
    returns: "Returns",
    expenses: "Expenses",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    weekly_returns: "Weekly Returns",
    nft_marketplace: "NFT Marketplace",
    save_listing: "Save Listing",
    share: "Share",
    add_to_wishlist: "Add to Wishlist",
    top_picks_label: "Top Picks",
    featured: "Featured",
    house_andromeda: "House Andromeda",
    bidders: "bidders",
    nfts_owned: "NFTs Owned",
    sort: "Sort",
    sort_default: "Default",
    price_low_high: "Price: Low → High",
    price_high_low: "Price: High → Low",
    profitable_only: "Profitable Only",
    change: "Change",
    status: "Status",
    profitable: "Profitable",
    at_loss: "At Loss",
    bid: "Bid",
    close: "Close",
    confirm_bid: "Confirm Bid",
    total_balance: "Total Balance",
    monthly_profit: "Monthly Profit",
    no_results: "No results found",
    profile_info: "Profile Information",
    display_name: "Display Name",
    email_address: "Email Address",
    bio: "Bio",
    website: "Website",
    save_changes: "Save Changes",
    saving: "Saving...",
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    update_password: "Update Password",
    updating: "Updating...",
    two_factor: "Two-Factor Authentication",
    danger_zone: "Danger Zone",
    delete_account: "Delete Account",
    sign_out: "Sign Out",
    social_connections: "Social Connections",
    api_access: "API Access",
    regenerate: "Regenerate",
    notification_prefs: "Notification Preferences",
    new_listings: "New Listings",
    price_drops: "Price Drops",
    bid_activity: "Bid Activity",
    weekly_report: "Weekly Report",
    marketing_emails: "Marketing Emails",
    search_properties: "Search properties...",
    no_properties_found: "No properties found",
    purchase_nft: "Purchase NFT",
    all: "All",
    mansion: "Mansion",
    villa: "Villa",
    apartment: "Apartment",
    commercial: "Commercial",
    total_properties: "Total Properties",
    portfolio_value: "Portfolio Value",
    total_eth: "Total ETH",
    avg_roi: "Avg ROI",
    property: "Property",
    price: "Price",
    roi: "ROI",
    details: "Details",
    actions: "Actions",
    manage: "Manage",
    no_properties_owned: "No properties owned yet",
    browse_marketplace: "Browse Marketplace",
    investment_overview: "Investment Overview",
    weekly_portfolio_curve: "Weekly portfolio performance",
    property_breakdown: "Property Breakdown",
    listings_by_status: "Listings by status",
    daily_distribution_log: "Daily Distribution Log",
    vs_baseline: "vs Baseline",
    above_target: "Above Target",
    below_target: "Below Target",
    export: "Export",
    custom: "Custom",
    months: ["January","February","March","April","May","June","July","August","September","October","November","December"],
    days_short: ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],
    today: "Today",
    upcoming_events: "Upcoming Events",
    no_events: "No events",
    nothing_scheduled: "Nothing scheduled for this day.",
    updating_password: "Updating...",
    update_password_btn: "Update Password",
    two_factor_auth: "Two-Factor Authentication",
    two_factor_desc: "Add an extra layer of security to your account.",
    danger_zone_desc: "These actions are permanent. Please proceed with caution.",
    delete_account_btn: "Delete Account",
    total_value: "Total Value",
    average_roi: "Average ROI",
    est_returns: "Est. Returns",
    owned_assets: "Owned Assets",
    portfolio_empty: "Your portfolio is empty",
    portfolio_empty_desc: "Head to the marketplace to start investing in properties.",
    explore_marketplace: "Explore Marketplace",
    purchase_price: "Purchase Price",
    current_value_est: "Current Value (Est)",
    wallet_balance: "Wallet Balance",
    deposit_funds: "Deposit Funds",
    amount_to_deposit: "Amount to deposit",
    successfully_deposited: "Successfully deposited",
    insufficient_funds: "Insufficient funds",
    confirm_payment: "Confirm Payment",
    buy_now: "Buy Now",
    processing: "Processing...",
  },
  fr: {
    dashboard: "Tableau de bord",
    marketplace: "Marché",
    houses: "Inventaire",
    analytics: "Analyses",
    portfolio: "Portefeuille",
    schedule: "Calendrier",
    settings: "Paramètres",
    logout: "Déconnexion",
    search_placeholder: "Rechercher...",
    my_cards: "Mes Cartes",
    top_picks: "Meilleurs Choix",
    language: "Langue",
    theme: "Thème",
    dark_mode: "Mode Sombre",
    light_mode: "Mode Clair",
    preferences: "Préférences",
    profile: "Profil",
    security: "Sécurité",
    connections: "Connexions",
    notifications: "Notifications",
    my_cards_title: "Mes Cartes",
    top_picks_title: "Meilleurs Choix",
    investment_stats: "Stats d'Investissement",
    my_portfolio: "Mon Portefeuille",
    total_investment: "Investissement Total",
    returns: "Rendements",
    expenses: "Dépenses",
    daily: "Quotidien",
    weekly: "Hebdomadaire",
    monthly: "Mensuel",
    weekly_returns: "Rendements Hebdo",
    nft_marketplace: "Marché NFT",
    save_listing: "Enregistrer l'annonce",
    share: "Partager",
    add_to_wishlist: "Ajouter aux favoris",
    top_picks_label: "Meilleurs choix",
    featured: "En vedette",
    house_andromeda: "Maison Andromeda",
    bidders: "enchérisseurs",
    nfts_owned: "NFT possédés",
    sort: "Trier",
    sort_default: "Par défaut",
    price_low_high: "Prix: croissant",
    price_high_low: "Prix: décroissant",
    profitable_only: "Rentables uniquement",
    change: "Variation",
    status: "Statut",
    profitable: "Rentable",
    at_loss: "En perte",
    bid: "Enchérir",
    close: "Fermer",
    confirm_bid: "Confirmer l'enchère",
    total_balance: "Solde Total",
    monthly_profit: "Profit Mensuel",
    no_results: "Aucun résultat trouvé",
    profile_info: "Informations du profil",
    display_name: "Nom d'affichage",
    email_address: "Adresse e-mail",
    bio: "Bio",
    website: "Site Web",
    save_changes: "Enregistrer",
    saving: "Enregistrement...",
    change_password: "Changer le mot de passe",
    current_password: "Mot de passe actuel",
    new_password: "Nouveau mot de passe",
    confirm_password: "Confirmer le mot de passe",
    update_password: "Mettre à jour",
    updating: "Mise à jour...",
    two_factor: "Authentification à deux facteurs",
    danger_zone: "Zone de danger",
    delete_account: "Supprimer le compte",
    sign_out: "Se déconnecter",
    social_connections: "Connexions sociales",
    api_access: "Accès API",
    regenerate: "Régénérer",
    notification_prefs: "Préférences de notification",
    new_listings: "Nouvelles annonces",
    price_drops: "Baisses de prix",
    bid_activity: "Activité d'enchères",
    weekly_report: "Rapport hebdomadaire",
    marketing_emails: "E-mails marketing",
    search_properties: "Rechercher des propriétés...",
    no_properties_found: "Aucune propriété trouvée",
    purchase_nft: "Acheter le NFT",
    all: "Tous",
    mansion: "Manoir",
    villa: "Villa",
    apartment: "Appartement",
    commercial: "Commercial",
    total_properties: "Total Propriétés",
    portfolio_value: "Valeur du Portefeuille",
    total_eth: "Total ETH",
    avg_roi: "ROI Moyen",
    property: "Propriété",
    price: "Prix",
    roi: "ROI",
    details: "Détails",
    actions: "Actions",
    manage: "Gérer",
    no_properties_owned: "Aucune propriété possédée",
    browse_marketplace: "Parcourir le Marché",
    investment_overview: "Investment Overview",
    weekly_portfolio_curve: "Performance hebdomadaire",
    property_breakdown: "Répartition des biens",
    listings_by_status: "Annonces par statut",
    daily_distribution_log: "Journal de distribution",
    vs_baseline: "vs Référence",
    above_target: "Au-dessus de l'objectif",
    below_target: "Sous l'objectif",
    export: "Exporter",
    custom: "Personnalisé",
    months: ["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"],
    days_short: ["Dim","Lun","Mar","Mer","Jeu","Ven","Sam"],
    today: "Aujourd'hui",
    upcoming_events: "Événements à venir",
    no_events: "Aucun événement",
    nothing_scheduled: "Rien de prévu pour ce jour.",
    updating_password: "Mise à jour...",
    update_password_btn: "Mettre à jour le mot de passe",
    two_factor_auth: "Authentification à deux facteurs",
    two_factor_desc: "Ajoutez une couche de sécurité supplémentaire à votre compte.",
    danger_zone_desc: "Ces actions sont permanentes. Veuillez procéder avec prudence.",
    delete_account_btn: "Supprimer le compte",
    total_value: "Valeur Totale",
    average_roi: "ROI Moyen",
    est_returns: "Rendements Est.",
    owned_assets: "Actifs Possédés",
    portfolio_empty: "Votre portefeuille est vide",
    portfolio_empty_desc: "Rendez-vous sur le marché pour commencer à investir.",
    explore_marketplace: "Explorer le Marché",
    purchase_price: "Prix d'Achat",
    current_value_est: "Valeur Actuelle (Est)",
    wallet_balance: "Solde du Portefeuille",
    deposit_funds: "Déposer des Fonds",
    amount_to_deposit: "Montant à déposer",
    successfully_deposited: "Déposé avec succès",
    insufficient_funds: "Fonds insuffisants",
    confirm_payment: "Confirmer le Paiement",
    buy_now: "Acheter Maintenant",
    processing: "Traitement...",
  },
  ar: {
    dashboard: "لوحة القيادة",
    marketplace: "السوق",
    houses: "المخزون",
    analytics: "التحليلات",
    portfolio: "المحفظة",
    schedule: "الجدول الزمني",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    search_placeholder: "ابحث عن العقارات...",
    my_cards: "بطاقاتي",
    top_picks: "أفضل الاختيارات",
    language: "اللغة",
    theme: "المظهر",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع الفاتح",
    preferences: "التفضيلات",
    profile: "الملف الشخصي",
    security: "الأمان",
    connections: "الاتصالات",
    notifications: "الإشعارات",
    my_cards_title: "بطاقاتي",
    top_picks_title: "أفضل الاختيارات",
    investment_stats: "إحصائيات الاستثمار",
    my_portfolio: "محفظتي",
    total_investment: "إجمالي الاستثمار",
    returns: "العوائد",
    expenses: "المصاريف",
    daily: "يومي",
    weekly: "أسبوعي",
    monthly: "شهري",
    weekly_returns: "عوائد أسبوعية",
    nft_marketplace: "سوق الـ NFT",
    save_listing: "حفظ الإعلان",
    share: "مشاركة",
    add_to_wishlist: "إضافة للمفضلة",
    top_picks_label: "أفضل الاختيارات",
    featured: "مميز",
    house_andromeda: "منزل أندروميدا",
    bidders: "مزايد",
    nfts_owned: "الـ NFTs المملوكة",
    sort: "ترتيب",
    sort_default: "افتراضي",
    price_low_high: "السعر: من الأقل إلى الأعلى",
    price_high_low: "السعر: من الأعلى إلى الأقل",
    profitable_only: "المربحة فقط",
    change: "التغيير",
    status: "الحالة",
    profitable: "مربح",
    at_loss: "خاسر",
    bid: "مزايدة",
    close: "إغلاق",
    confirm_bid: "تأكيد المزايدة",
    total_balance: "إجمالي الرصيد",
    monthly_profit: "الربح الشهري",
    no_results: "لا توجد نتائج",
    profile_info: "معلومات الملف الشخصي",
    display_name: "الاسم المستعار",
    email_address: "البريد الإلكتروني",
    bio: "النبذة الشخصية",
    website: "الموقع الإلكتروني",
    save_changes: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    change_password: "تغيير كلمة المرور",
    current_password: "كلمة المرور الحالية",
    new_password: "كلمة المرور الجديدة",
    confirm_password: "تأكيد كلمة المرور",
    update_password: "تحديث كلمة المرور",
    updating: "جاري التحديث...",
    two_factor: "المصادقة الثنائية",
    danger_zone: "منطقة الخطر",
    delete_account: "حذف الحساب",
    sign_out: "تسجيل الخروج",
    social_connections: "التواصل الاجتماعي",
    api_access: "وصول API",
    regenerate: "إعادة إنشاء",
    notification_prefs: "تفضيلات الإشعارات",
    new_listings: "عقارات جديدة",
    price_drops: "انخفاض الأسعار",
    bid_activity: "نشاط المزايدة",
    weekly_report: "التقرير الأسبوعي",
    marketing_emails: "رسائل تسويقية",
    search_properties: "بحث عن عقارات...",
    no_properties_found: "لم يتم العثور على عقارات",
    purchase_nft: "شراء NFT",
    all: "الكل",
    mansion: "قصر",
    villa: "فيلا",
    apartment: "شقة",
    commercial: "تجاري",
    total_properties: "إجمالي العقارات",
    portfolio_value: "قيمة المحفظة",
    total_eth: "إجمالي ETH",
    avg_roi: "متوسط ROI",
    property: "العقار",
    price: "السعر",
    roi: "ROI",
    details: "التفاصيل",
    actions: "الإجراءات",
    manage: "إدارة",
    no_properties_owned: "لا تملك عقارات بعد",
    browse_marketplace: "تصفح السوق",
    investment_overview: "نظرة عامة على الاستثمار",
    weekly_portfolio_curve: "أداء المحفظة الأسبوعي",
    property_breakdown: "توزيع العقارات",
    listings_by_status: "العقارات حسب الحالة",
    daily_distribution_log: "سجل التوزيع اليومي",
    vs_baseline: "مقارنة بالأساس",
    above_target: "فوق الهدف",
    below_target: "تحت الهدف",
    export: "تصدير",
    custom: "مخصص",
    months: ["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"],
    days_short: ["أحد","إثنين","ثلاثاء","أربعاء","خميس","جمعة","سبت"],
    today: "اليوم",
    upcoming_events: "الأحداث القادمة",
    no_events: "لا توجد أحداث",
    nothing_scheduled: "لا يوجد شيء مقرر لهذا اليوم.",
    updating_password: "جاري التحديث...",
    update_password_btn: "تحديث كلمة المرور",
    two_factor_auth: "المصادقة الثنائية",
    two_factor_desc: "أضف طبقة إضافية من الأمان إلى حسابك.",
    danger_zone_desc: "هذه الإجراءات دائمة. يرجى المتابعة بحذر.",
    delete_account_btn: "حذف الحساب",
    total_value: "القيمة الإجمالية",
    average_roi: "متوسط ROI",
    est_returns: "العوائد المتوقعة",
    owned_assets: "الأصول المملوكة",
    portfolio_empty: "محفظتك فارغة",
    portfolio_empty_desc: "توجه إلى السوق لبدء الاستثمار في العقارات.",
    explore_marketplace: "استكشف السوق",
    purchase_price: "سعر الشراء",
    current_value_est: "القيمة الحالية (تقديرية)",
    wallet_balance: "رصيد المحفظة",
    deposit_funds: "إيداع الأموال",
    amount_to_deposit: "المبلغ المراد إيداعه",
    successfully_deposited: "تم الإيداع بنجاح",
    insufficient_funds: "رصيد غير كافٍ",
    confirm_payment: "تأكيد الدفع",
    buy_now: "شراء الآن",
    processing: "جاري المعالجة...",
  },
};

const PreferencesContext = createContext<PreferencesContextType | undefined>(undefined);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [theme, setThemeState] = useState<Theme>("light");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = (localStorage.getItem("app_lang") as Language) || "en";
    const savedTheme = (localStorage.getItem("app_theme") as Theme) || "light";
    
    setLanguageState(savedLang);
    document.documentElement.dir = savedLang === "ar" ? "rtl" : "ltr";
    
    setThemeState(savedTheme);
    if (savedTheme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, []);

    const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app_lang", lang);
    // Optional: add dir attribute for Arabic
    if (lang === "ar") {
      document.documentElement.dir = "rtl";
    } else {
      document.documentElement.dir = "ltr";
    }
  };

  const setTheme = (t: Theme) => {
    setThemeState(t);
    localStorage.setItem("app_theme", t);
    if (t === "dark") document.documentElement.classList.add("dark");
    else document.documentElement.classList.remove("dark");
  };

  const t = (key: any): any => {
    // @ts-ignore
    return translations[language][key] || translations["en"][key];
  };

  return (
    <PreferencesContext.Provider value={{ language, setLanguage, theme, setTheme, t }}>
      {children}
    </PreferencesContext.Provider>
  );
}

export const usePreferences = () => {
  const context = useContext(PreferencesContext);
  if (!context) throw new Error("usePreferences must be used within PreferencesProvider");
  return context;
};
